name : CI

on:
  push:
    branches: [main, master, platforms-01-rafal]
  pull_request:
    branches: [main, master, platforms-01-rafal]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint app
        run: npm run lint

      - name: Build app
        run: npm run build

      - name: Test app
        run: npm test

      - name: Finish message
        run: echo "CI pipeline completed successfully!"

      - name: Build Docker image
        run: docker build -t test-image .

      - name: Start container
        run: docker run -d --name test-container -p 3001:3001 test-image

      - name: Check container health
        run: curl --fail --retry 10 --retry-delay 1 --retry-connrefused http://localhost:3001/health

      - name: Stop container
        if: always()
        run: docker rm -f test-container
