name : CI

on:
  push:
    branches: [main, master, platforms-01-rafal]
  pull_request:
    branches: [main, master, platforms-01-rafal]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint app
        run: npm run lint

      - name: Build app
        run: npm run build

      - name: Test app
        run: npm test

      - name: Finish message
        run: echo "CI pipeline completed successfully!"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker image
        run: |
          IMAGE_TAG="${GITHUB_SHA::12}"
          docker build -t team8-frontend:${IMAGE_TAG} .
